<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>annotations</Nullable>
    <AssemblyName>NRTDP.tdReportConverter</AssemblyName>
    <RootNamespace>NRTDP.tdReportConverter</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Company>Northwestern University</Company>
    <Authors>NRTDP</Authors>
    <PackageId>NRTDP.tdReportConverter</PackageId>
    <Version>1.0.1</Version>
    <Description>A package for converting tdReports into mzidentml files</Description>
    <Copyright>NRTDP</Copyright>
    <PackageTags>mzIdentml, tdReport</PackageTags>
    <RepositoryUrl>https://github.com/NRTDP/tdReport-to-mzIdentML</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>

</Project>
