name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    - name: Restore
      run: dotnet restore src/NRTDP.ReportConverter.sln
    - name: Build
      run: dotnet build src/NRTDP.ReportConverter.sln -c Release --no-restore
